package dev.shaukat.RagApplicationService.file;

public enum FileStatus {
    UPLOADED, UPLOAD_FAILED,FILE_ALREADY_EXISTS ,NOT_SUPPORTED, ADDING_TO_COLLECTION, ADDED_TO_COLLECTION, FAILED_ADDING_TO_COLLECTION
}
